### ISSUE TITLE
楼主，都没上传完全吧！功能清单和res目录都没有

### ISSUE THREAD

**Issue by liuwen370494581** [Zzzia/EasyBook#1]
如题 楼主会上传完全吗？对这个项目挺赶兴趣的

**Comment by Zzzia** [comment]
嗯，是的，这个只是java版本的，只有命令行和gui。android版本还没有上传，其实安卓就是包装了一下，直接把这些代码复制过去的

**Comment by Zzzia** [comment]
https://github.com/Zzzia/Book
建了个新仓库

**Comment by liuwen370494581** [comment]
感谢楼主！爬取的小说html有什么技巧嘛？

**Comment by Zzzia** [comment]
@liuwen370494581 我感觉爬小说没什么难度，简单的直接用正则提取关键信息，复杂一点的布局jsoup用解析。就是有的小说网站有防爬措施，用js延迟加载，或者必须登录，就很麻烦了

**Comment by Zzzia** [comment]
@liuwen370494581 一般的小说html都在一个div里面，用p或者br标签分割段落，把那个div提取出来，在string.split或者再用一次正则匹配就行。提取的内容很可能有缩进符，广告啥的，需要清理掉。我的思路是在每个站点的解析里顺手清理广告，然后在封装的类里统一清理多余的缩进。

**Comment by Zzzia** [comment]
@liuwen370494581 前几天写了一篇博客记录一些坑和细节，但是怎么解析没有写，可以参考下
https://blog.csdn.net/qq_36168049/article/details/83867388

**Comment by liuwen370494581** [comment]
感谢楼主给的思路！
